jobs:
  GetTestFiles:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/checkout@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: GetTestFiles
      run: |
        python Agent.py --api_key ${{ secrets.API_KEY }} --path ./